[package]
name = "fdtab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
ms_std = { workspace = true, features = ["alloc_def", "panic_def"] }
lazy_static = "*"
spin = "*"
ms_hostcall = { workspace = true }
