# cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "msvisor",
    "ms_hostcall",
    "common_service/fs",
    "user/ms_std",
    "user/hello_world",
    "user/should_panic",
]

[workspace.dependencies]
ms_std = { path = "user/ms_std" }
ms_hostcall = { path = "ms_hostcall" }
native_fs = { path = "common_service/fs" }

# [profile.dev.package.hello_world]
