# cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "msvisor",
    "gen-file",
    "ms_hostcall",

    "ms_std",

    "common_service/fdtab",
    "common_service/stdio",
    "common_service/socket",

    "user/hello_world",
    "user/should_panic",
    "user/simple_http",
]
default-members = ["msvisor"]

[workspace.dependencies]
msvisor = { path = "msvisor" }

ms_hostcall = { path = "ms_hostcall" }
ms_std = { path = "ms_std" }

fstab = { path = "common_service/fdtab" }

smoltcp = { path = "smoltcp", default-features = false, features = [
    "log",
    "std",
    "medium-ethernet",
    "medium-ip",
    "phy-tuntap_interface",
    "proto-ipv4",
    "socket-tcp",
] }

# [profile.dev.package.hello_world]
