# cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "msvisor",
    "gen-file",
    "ms_hostcall",

    "common_service/ms_std",
    "common_service/fs",
    "common_service/fdtab",
    "common_service/stdio",

    "user/hello_world",
    "user/should_panic",
]
default-members = ["msvisor"]


[workspace.dependencies]
msvisor = { path = "msvisor" }

ms_hostcall = { path = "ms_hostcall" }

ms_std = { path = "common_service/ms_std" }
native_fs = { path = "common_service/fs" }
fstab = { path = "common_service/fdtab" }

# [profile.dev.package.hello_world]
