# cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "msvisor",
    "gen-file",
    "ms_hostcall",

    "ms_std",
]
exclude = [
    "user/",
    "common_service/"
]
default-members = ["msvisor"]

[workspace.dependencies]
msvisor = { path = "msvisor" }

ms_hostcall = { path = "ms_hostcall" }
ms_std = { path = "ms_std" }

fstab = { path = "common_service/fdtab" }
