[package]
name = "msvisor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "*"
anyhow = "*"
lazy_static = "*"
ms_hostcall = { workspace = true }
log = "*"
env_logger = "*"
xmas-elf = "*"                                   # use to parse dynlib elf file.
nix = "*"                                        # use to call mmap.
serde = { version = "*", features = ["derive"] }
serde_json = "*"
