[package]
name = "stdio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
ms_hostcall = { path = "../../ms_hostcall" }


[features]
mpk = []
default = []