[package]
name = "wasmtime_hello"
version = "0.1.0"
edition = "2021"
build = "../../build_user.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
as_std = { path = "../../as_std", features = ["panic_def", "alloc_def"] }
as_hostcall = { path = "../../as_hostcall", features = ["signal"] }
sjlj = { version="0.1.3" }
wasmtime = { version = "=21.0.0", default-features = false, features = [
    "runtime",
    "gc",
    "component-model",
] }

[features]
mpk = ["as_std/mpk"]

default = []
