[package]
name = "handler"
version = "0.1.0"
authors = ["Piotr Roslaniec <p.roslaniec@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.13.2"
rust-s3 = { version = "0.33.0", default-features = false, features = [
    "tokio-rustls-tls",
] }
tokio = "1.33.0"
