[package]
name = "handler"
version = "0.1.0"
authors = ["Piotr Roslaniec <p.roslaniec@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.108"
rust-s3 = { git = "https://github.com/durch/rust-s3", default-features = false, features = [
    "sync",
    "sync-rustls-tls",
] }
