[package]
name = "ms_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]

[dependencies]
ms_hostcall = { workspace = true }

# once_cell = "*"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
buddy_system_allocator = "0.9"
unwinding = { version = "0.1.7", features = [
    "panic-handler",
    "personality",
], optional = true }
